version: '3'
services:
    web:
        build: .
        volumes:
          - .:/code
        depends_on:
          - db
        entrypoint: ["./entrypoint.sh"]
        ports:
          - "8000:8000"
        expose:
          - "8000"
    db:
        image: postgres:latest
        environment:
          POSTGRES_USER: ksradau
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: ksradau
        ports:
          - "5433:5432"
        restart: always
