default:
  AWS_ACCESS_KEY_ID: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SITE_ID: 0

development:
  AWS_S3_REGION_NAME: "us-east-1"
  SECRET_KEY: ""
  DEBUG: true
  SITE_ID: 5
  DATABASE_URL: ""

production:
  AWS_S3_REGION_NAME: "us-east-1"
  DEBUG: false
  SITE_ID: 5
  SECRET_KEY: ""
  DATABASE_URL: ""
