# Generated by Django 3.1.7 on 2021-03-03 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homeworkdone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_comment', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkdone',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='student_homework_done', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_mark', to='auth.user'),
            preserve_default=False,
        ),
    ]
