# Generated by Django 3.1.7 on 2021-03-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210303_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkdone',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_done', to='api.homework'),
        ),
    ]
